### ISSUE TITLE
Acompanhar Conversão Analitcs e Facebook 

### ISSUE THREAD

**Issue by raf-rodrigues** [YapayPagamentos/woo-yapay#1]
Como acompanhar uma conversão (Venda) pelo Yapay. Tentei configura mas não é possivel acompanhar a conversão. Aparece como Pageview tanto no Facebook como no Google Analitcs.

Tentamos criar uma pagina de finalização de pedido, mas o plugin subscreve com uma pagina própria e não é possivel trackear qualquer tipo de conversão ( Boleto, Cartao de Credito ou Transferencia).

**Comment by aguiarrdev** [comment]
@raf-rodrigues Ainda enfrenta o mesmo problema ou encontrou uma forma de contorná-lo?

**Comment by ThalitaNsc** [comment]
Por falta de retorno estamos encerrando essa issue.
