### ISSUE TITLE
bug de parcelamento

### ISSUE THREAD

**Issue by chukran** [YapayPagamentos/woo-yapay#12]
![image](https://user-images.githubusercontent.com/55173896/68923173-6b7d9780-075c-11ea-811c-f05968778e4d.png)

quando da algum erro o parcelamento aparece assim meio zuado

queria saber como é que faz pra não exibir com juros ou sem juros após preço do produto 

não quero deixar meu cliente pensar muito sobre isso é ver o preço e fazer o pedido to tentando testar aqui e a cada erro é necessário escolher novamente o parcelamento façam a correção por favor sobre isto.

**Comment by aguiarrdev** [comment]
Olá @chukran. Infelizmente não temos essa opção, mas caso precise é possível adicionar uma estilização para evitar que os textos apareçam.

psc @ThalitaNsc

**Comment by ThalitaNsc** [comment]
Boa Tarde o erro não ocorre mais.
