### ISSUE TITLE
Taxes issue

### ISSUE THREAD

**Issue by SkynetCom** [YapayPagamentos/woo-yapay#14]
Hi.... we have Yapay into 3 woocommerce stores, and in all of them orders ammount are sended to Yapay WITHOUT taxes... all orders details are OK, but by example:
WC Order Total (inc taxes): R$540,13
Order payment into Yapay: R$ 469,69

Shipping cost & discounts are ok, but no taxes in any order

Did you know about that?

**Comment by SkynetCom** [comment]
Nobody ?????????

**Comment by wagnerjaccoud** [comment]
my version is more functional and handles everything better

Access: https://github.com/wagnerjaccoud/woo-yapay

**Comment by aguiarrdev** [comment]
@SkynetCom  Resolvido na PR #23 | Solved in PR #23

**Comment by devaguia** [comment]
psc @ThalitaNsc

**Comment by ThalitaNsc** [comment]
Encerrando pois já está disponivel na atualização do nosso plugin tal correção.
