### ISSUE TITLE
Incluir transaction[max_split_transaction] na solicitação da API

### ISSUE THREAD

**Issue by ezanatta-yapay** [YapayPagamentos/woo-yapay#15]
Ao criar uma transação, não é enviado o valor transaction[max_split_transaction], assim, quando a transação é recuperada por e-mail, não é seguida a regra de número máximo de parcelas.

É uma configuração que consta na API, na criação da transação, mas acaba não passando na API.

**Comment by abnava** [comment]
issue criada no backlog.

**Comment by abnava** [comment]
Versão 0.5.9 está com a solicitação
