### ISSUE TITLE
Descontos por tipo de pagamento não é considerado pelo plugin

### ISSUE THREAD

**Issue by sdsanches** [YapayPagamentos/woo-yapay#18]
Olá, 

Utilizamos o plugin em nossa loja, praticamos o desconto de 5% para clientes que efetuam o pagamento via boleto, essa é uma prática muito comum em todos os e-commerces. 

Como não existe essa funcionalidade, utilizamos um plugin de terceiros para aplicar o desconto dependendo do tipo de pagamento escolhido, fizemos alguns testes e o valor do desconto é calculado corretamente em nosso site, então o cliente finaliza o pedido.

É neste momento que o problema aparece, ao finalizar o pedido, no valor de R$95,00 (já com o desconto), o valor que aparece na transação da YaPay é R$100,00, ou seja, parece que recalcula novamente não considerando o desconto...

Poderiam verificar isso por gentileza?

O plugin que utilizamos para aplicar o desconto é o do link abaixo:
https://br.wordpress.org/plugins/woo-payment-discounts/

**Comment by tiago-123** [comment]
Procurei o github para relatar o mesmo problema e vi que já havia uma solicitação em aberto. Isso precisa ser arrumado o quanto antes. O plugin do Claudio Sanches de desconto por cupons tem alguns bugs e não é uma opção para nossa loja.
Estamos utilizando o plugin https://br.wordpress.org/plugins/checkout-fees-for-woocommerce/ que funciona muito bem e não tem bugs em nosso setup.
Porém o desconto aplicado por esse plugin não é identificado pelo Yapay.

**Comment by abnava** [comment]
Vou realizar alguns testes nesse plugin e já volto aqui!

**Comment by abnava** [comment]
[WooCommerce] Atualização plugin

https://yapaypagamentos.github.io/integracao-news/woocommerce/yapay-woocommmerce-v0.6.1.html
