### ISSUE TITLE
Precisamos de uma alternativa para o plugin do Cláudio Sanches

### ISSUE THREAD

**Issue by tiago-123** [YapayPagamentos/woo-yapay#19]
Olá,

Atualmente o plugin do Yapay para WooCommerce exige a instalação do plugin "Brazilian Market on WooCommerce" do Cláudio Sanches. Porém esse plugin está abandonado e sem atualizações desde 2019!!! Parou de funcionar hoje na nossa loja. Um total desespero pois precisamos dessa droga de plugin do Cláudio Sanches para o e-commerce funcionar.

Nós teríamos como alternativa o plugin JetWooBuilder da Crocoblock, que possibilita editar e personalizar os campos do Checkout. Existe alguma forma de integrar o Yapay com esse plugin?

Por favor, precisamos de uma saída para esse problema.
Obrigado,
Tiago.

**Comment by denisgomesfranco** [comment]
...em 2022 o plugin Brazilian Market segue funcionando em todas as lojas que desenvolvi. Todos os outros plugins brasileiros dependem dele, e até mesmo ERPs como o Tiny. Não ter atualização faz um tempo não significa que ele deixou de funcionar, tenho certeza de que se isso de fato acontecer alguém irá atualizá-lo.

Quanto a não funcionar na sua loja, seria necessário avaliar o que foi que aconteceu.

**Comment by aguiarrdev** [comment]
@ThalitaNsc Podemos encerrar este.

**Comment by ThalitaNsc** [comment]
Encerrando pois a correção não se aplica.
