### ISSUE TITLE
Lentidão excessiva na abertura do Checkout

### ISSUE THREAD

**Issue by diogodaluz** [YapayPagamentos/woo-yapay#20]
O plugin gera uma lentidão absurda até que o cliente possa interagir com o checkout. (fica aguardando uma requisição)

Analisando o JavaScript, percebi que a lentidão aparentemente vem de uma consulta feita pelo plugin da Yapay na KONDUTO e tb na CLEARSALE.

Aliás, não entendi pq os 2.

**Comment by diogodaluz** [comment]
Segue imagem. Observe no canto esquerdo inferior, fica carregando KONDUTO.

![image](https://user-images.githubusercontent.com/11308015/144308855-ecda6f26-41c4-43eb-997d-d47e0661de56.png)

**Comment by diogodaluz** [comment]
Analisando as Ferramentas do Desenvolvedor, notei que essa requisição parte de:

https://static.traycheckout.com.br/js/finger_print.js

Esse Javascript no caso estabelece conexão com Clearsale e Konduto. Ambas lentíssimas, mas a Konduto chega a dar 14s

**Comment by aguiarrdev** [comment]
@diogodaluz 
Infelizmente essas requisições são necessárias para o funcionamento correto do plugin na geração da fingerprint, como pode ver na documentação da API Yapay: [link](https://intermediador.dev.yapay.com.br/#/transacao-fingerprint).

Realizei vários testes e não obtive um tempo de resposta significativo. Todas as requisições estavam funcionando e com tempo de resposta padrão. Tavez seja algo pontual que ocorreu na época da abertura da issue.

@ThalitaNsc Se possível pode fechar

**Comment by ThalitaNsc** [comment]
Encerrando o ocorrido pois não identificamos gaps de lentidões oriundas do nosso plugin.
