### ISSUE TITLE
Plugin repassando "fees" do pedido como se fossem descontos

### ISSUE THREAD

**Issue by denisgomesfranco** [YapayPagamentos/woo-yapay#21]
Como sabemos, no Woocommerce é possível inserir acréscimos (fees ou taxas) em pedidos de forma programática. O plugin da Yapay atualmente busca estas "fees" no pedido, porém envia-as como se fossem descontos. Ou seja: se o valor do pedido é R$ 10 e temos R$ 2 em taxas acrescentadas, o Yapay processa a transação como sendo R$ 8 e não como sendo R$ 12.

O erro na lógica parece estar localizado no arquivo https://github.com/YapayPagamentos/woo-yapay/blob/master/woo-yapay/class-wc-yapay_intermediador-creditcard-gateway.php a partir da linha 349. Mas verifiquei rapidamente e parece que isso também ocorre nas outras formas de pagamento da Yapay e não apenas no cartão de crédito.

Observe que a linha 353 puxa especificamente as "fees" do pedido, ou seja, o plugin sabe da existência delas. O problema parece estar é no repasse disso para a API.

**Comment by aguiarrdev** [comment]
Opa @denisgomesfranco!
Estamos verificando o seu chamado. Fique atento, qualquer novidades te notificaremos por aqui.

**Comment by denisgomesfranco** [comment]
Excelente @aguiarrdev , muito obrigado!

**Comment by aguiarrdev** [comment]
@denisgomesfranco Após analisar o problema cheguei em uma solução onde as taxas negativas, junto com os descontos de coupons são enviados para a Yapay como um desconto no pedido, mas as taxas com o valor positivo são enviadas realmente como taxas.
Acredito que isso vá resolver o problema que está enfrentando.

**Comment by ThalitaNsc** [comment]
Encerrado pois o problema encontra-se corrigido.
