### ISSUE TITLE
Pagamento por PIX não funciona com cadastros PJ

### ISSUE THREAD

**Issue by denisgomesfranco** [YapayPagamentos/woo-yapay#22]
(Esse problema foi reportado inicialmente em 29 de março de 2022 na [aba de suporte do wordpress.org](https://wordpress.org/support/topic/pagamento-por-pix-nao-funciona-com-cadastros-pj/))

"Um de meus lojistas relatou este problema. Quando alguém faz a compra na loja virtual utilizando um cadastro de pessoa jurídica, este cadastro obviamente conterá apenas o CNPJ e não o CPF, e ao finalizar a compra com PIX o módulo do Yapay retorna o erro de que o CPF não foi preenchido."

A solução para isso é muito simples: ou a API da Yapay passe a permitir compras por clientes que possuam apenas CNPJ, ou o plugin da Yapay solicite o CPF do comprador junto ao aviso do pix exibido pelo plugin.

**Comment by aguiarrdev** [comment]
Boa tarde @denisgomesfranco! 
Já estamos verificando o problema reportado, assim que tivermos uma solução para o plugin ou alguma informação nova, te avisaremos por aqui.

**Comment by denisgomesfranco** [comment]
Perfeito @aguiarrdev , aguardo!

**Comment by ThalitaNsc** [comment]
Problema corrigido.
