### ISSUE TITLE
Sugestão simples para padronizar boleto, pix e cartão

### ISSUE THREAD

**Issue by yassersous** [YapayPagamentos/woo-yapay#25]
Na opção de pagamento  por boleto, há um label com o texto "Selecione a forma de pagamento *" mesmo já selecionada a forma de pagamento. Pode parecer pouco, mas para vendas online qualquer detalhe é motivo de desistência da compra. Se já foi selecionado, não há motivo de o sistema pedir 'novamente' para selecionar. Veja que para Pix, existe a frase "Forma de pagamento *". Não há padrão. Tentei usar javascript para sobrescrever e eliminar esses textos, mas os métodos de pagamento carregam em separado, então sobrescrevem meu código.

**Comment by aguiarrdev** [comment]
Olá @yassersous. Obrigado pela sugestão! Estamos verificando a melhor forma de resolver esta situação, assim que corrigirmos ou tivermos mais informações te notificaremos por aqui.

**Comment by yassersous** [comment]
Obrigado por me responder Matheus! Vou enviar print de como fica o checkout com o plugin do mercado pago (apenas para referência se você quiser usar alguma ideia meu amigo).
![C9518D09-9B8B-4644-88C2-90D050D356E7](https://user-images.githubusercontent.com/51012694/203840918-1aa23618-422d-4b14-83ec-292e1e48e1aa.jpeg)
![B938F072-9C6F-4DE2-B05A-ED06EFF761BA](https://user-images.githubusercontent.com/51012694/203840921-8e823932-de96-4b0f-906f-053cc51600ac.jpeg)
![6BDC3D67-01D3-4620-BEEB-6DD62685E41E](https://user-images.githubusercontent.com/51012694/203840922-275d2e77-6b25-45e4-9342-e397020e5df3.jpeg)

**Comment by yassersous** [comment]
Me desculpa pela pergunta idiota, mas o que é PR?

Cliquei aqui nesse link https://github.com/YapayPagamentos/woo-yapay/pull/29 e vi que alterou a padronização dos métodos de pagamento. MUITO OBRIGADO POR ISSO! Se eu puder falar sobre apenas 1 detalhe bem simples, é o texto "A maneira mais fácil e segura e comprar pela internet.". Faltou a letra D na palavra DE antes de COMPRAR. Só isso meu amigo.

**Comment by aguiarrdev** [comment]
Sobre o texto errado, vou alterá-lo, mas há como você controlar o texto que aparece pelo cliente. Você pode mudá-lo nas configurações de cada método de pagamento individualmente.

**Comment by yassersous** [comment]
Obrigado pelas explicações meu amigo! Isso significa que qualquer pessoa pode fazer alterações no plugin original e adicionar um PR para o dono do plugin?

Sobre o texto show! Entendi sim, faz sentido. Por aqui mesmo podemos alterar não me lembrava disso.

Desde já agradeço pelas alterações meu amigo..

**Comment by aguiarrdev** [comment]
@yassersous Teoricamente todos podem subir PRs, mas no meu caso faço parte da equipe que da manutenção para o plugin.

**Comment by yassersous** [comment]
Legal Matheus, obrigado pelas informações!

**Comment by ThalitaNsc** [comment]
Problema corrigido.
