### ISSUE TITLE
Pagamentos por boleto

### ISSUE THREAD

**Issue by yassersous** [YapayPagamentos/woo-yapay#26]
Na compra de um produto por boleto, o cliente não tem a possibilidade de acessar novamente seu boleto na página MINHA CONTA e em nenhum outro lugar no site. Existe a possibilidade de implementar? Aqui na empresa optamos por continuar usando outro meio de pagamento para Boleto e Pix em função desse problema, e gostaríamos de concentrar tudo na Vindi.

**Comment by aguiarrdev** [comment]
Olá @yassersous. Vamos verificar a possibilidade de implementar a funcionalidade questionada. Assim possível te retornaremos.

**Comment by yassersous** [comment]
Obrigado por sua resposta Matheus! Em anexo eu enviei algumas telas do plugin do Mercado Pago. As páginas de obrigado do Pix e boleto e as páginas da Minha conta, onde o usuário pode baixar o boleto ou ter acesso novamente ao código Pix (te enviei apenas para referência meu algo, caso queira usar alguma ideia).

OBRIGADO PIX
![45C405C4-2EF5-42CF-B119-847E96429248](https://user-images.githubusercontent.com/51012694/203843190-c5ad684a-76b1-4cdf-92a4-9a3fd0314a9c.jpeg)

OBRIGADO BOLETO
![57EB0425-764A-4992-9FAA-0FE353227400](https://user-images.githubusercontent.com/51012694/203843334-c604ff07-4953-4cb8-8319-263192de996b.jpeg)
![446EA45F-E198-43B0-9FBB-F0EE4F82C1BA](https://user-images.githubusercontent.com/51012694/203843374-34782ce9-ce9b-4ec7-ac8e-bd6a294629f8.jpeg)

MINHA CONTA PIX
![D4F02B54-E961-4DFA-8230-32890818CBAB](https://user-images.githubusercontent.com/51012694/203843483-234003ef-ed59-4383-9540-6ad611e6816a.jpeg)

MINHA CONTA BOLETO
![A3699926-945C-4083-942C-1F38CBABF6F2](https://user-images.githubusercontent.com/51012694/203843591-f9ff5e32-6c1c-4ea9-8e38-04cc6b1f4a74.jpeg)

**Comment by aguiarrdev** [comment]
@yassersous 
Adicionei uma nova Pull Request para esse problema que relatou. Ela passará por uma validação e caso passe será disponibilizada em versões futuras.

**Comment by yassersous** [comment]
Obrigado meu amigo!
