### ISSUE TITLE
Tag ul com order_details quebrando página de OBRIGADO

### ISSUE THREAD

**Issue by yassersous** [YapayPagamentos/woo-yapay#27]
Existe uma tag ul adicionada à página de obrigado que foi codada de forma que está quebrando as páginas de obrigado.

Para cartão a tag traz número de transação, bandeira do cartão e pagamento em X vezes. Para boleto traz o número da transação, botão para imprimir boleto (que puxa css do próprio tema, o que é legal) e 'linha digitável' do boleto). Para pix traz o texto 'Pix Copia e Cola', um input com o código e o QR code abaixo.

Existe a possibilidade de reescreverem essa parte do código?

Eu fiz uma gambiarra e adicionei um código javascript para melhorar essa apresentação para o usuário para quem está co esse problema e quer implementar uma solução TEMPORÁRIA (segue abaixo, e me desculpe a gambiarra mas eu não sou programador!!! Fiz o que pude):

```
add_action( 'wp_footer', function () { ?>
<script>
	
	/* Arruma cartão na página de obrigado */
	const text0 = 'Bandeira de Cartão';
	for (const li of document.querySelectorAll('li')) {
	  if (li.textContent.includes(text0)) {
		li.parentElement.style.display = "none";
	  }
	}
	
	/* Arruma boleto na página de obrigado */
	var tagp1 = document.createElement('p');
	var text_tagp1 = document.createTextNode('Ótimo, processamos seu pedido. Agora complete o pagamento do boleto para que possamos aprovar o pedido. CLIQUE NO BOTÃO ABAIXO');
	const text1 = 'Número da Transação';
	const text2 = 'Linha Digitável do Boleto';
	const text3 = 'Imprimir Boleto'
	for (const li of document.querySelectorAll('li')) {
	  if (li.textContent.includes(text2)) {
		li.style.display = "none";
		li.parentElement.style.marginLeft = "0";
		li.parentElement.style.listStyleType = "none";
		tagp1.appendChild(text_tagp1);
		li.parentElement.prepend(tagp1);
		for(const li2 of li.parentElement.querySelectorAll('li')) {
			 if (li2.textContent.includes(text1)) {
				 li2.style.display = "none";
			 }
		}
	  }
	  if (li.textContent.includes(text2)) {
		li.style.display = "none";
	  }
	}
	for (const a of document.querySelectorAll('a')) {	
	  if (a.textContent.includes(text3)) {
		a.style.color = "#ffffff";
		a.style.fontWeight = "bold";
	  }
	}
	
	/* Arruma Pix na página de obrigado */
	var tagp2 = document.createElement('p');
	var text_tagp2 = document.createTextNode('Agora, é só pagar com o Pix para finalizar a sua compra.');
	var tagp3 = document.createElement('p');
	var text_tagp3 = document.createTextNode('Como pagar com Pix:');
	var tagp4 = document.createElement('p');
	var text_tagp4 = document.createTextNode('1 - Acesse o app ou site do seu banco');
	var tagp5 = document.createElement('p');
	var text_tagp5 = document.createTextNode('2 - Busque a opção de pagar com Pix');
	var tagp6 = document.createElement('p');
	var text_tagp6 = document.createTextNode('3 - Leia o QR code ou o código Pix');
	var tagp7 = document.createElement('p');
	var text_tagp7 = document.createTextNode('4 - Pronto! Você verá a confirmação de pagamento');
	var tagp8 = document.createElement('p');
	var text_tagp8 = document.createTextNode('ESCANEIE O QR CODE OU COPIE O CÓDIGO PIX ABAIXO:');
	const text4 = 'Após realizar o pagamento do PIX';
	for (const p of document.querySelectorAll('p')) {	
	  if (p.textContent.includes(text4)) {
		p.parentElement.style.display = "none";
		p.parentElement.parentElement.style.marginLeft = "0";
		p.parentElement.parentElement.style.listStyleType = "none";
		tagp8.appendChild(text_tagp8);
		p.parentElement.parentElement.prepend(tagp8);
		tagp7.appendChild(text_tagp7);
		p.parentElement.parentElement.prepend(tagp7);
		tagp6.appendChild(text_tagp6);
		p.parentElement.parentElement.prepend(tagp6);
		tagp5.appendChild(text_tagp5);
		p.parentElement.parentElement.prepend(tagp5);
		tagp4.appendChild(text_tagp4);
		p.parentElement.parentElement.prepend(tagp4);
		tagp3.appendChild(text_tagp3);
		p.parentElement.parentElement.prepend(tagp3);
		tagp2.appendChild(text_tagp2);
		p.parentElement.parentElement.prepend(tagp2);
	  }
	}


</script>
<?php } );
```

**Comment by aguiarrdev** [comment]
Bom dia @yassersous. Tudo bem?
Consegue me enviar uma imagem da quebra, sem a sua correção e depois com a sua correção?

**Comment by yassersous** [comment]
Olá meu amigo, tudo certo por aqui! E você como está?

Desculpe pela demora, hoje o dia foi muito corrido.

Obrigado por sua resposta!

E anexo enviei print das telas de obrigado e dos trechos de códigos antes da minha alteração. E enviei também print das telas depois da minha alteração.

Dá pra perceber que a página de obrigado para cartão de crédito realmente não tem erros (inclusive, dentro da tag ul do cartão não há tantas tags <br> quanto nos outros métodos de pagamento. Não sei se isso altera algo, enfim, te mandei prints). Os problemas ocorrem para Boleto e Pix.

Perceba que na página de obrigado do boleto, a linha do código do boleto ultrapassa os limites da página dependendo do dispositivo que você usa. Perceba também que na página de obrigado do Pix, as "bolinhas" dos elementos <li> estão em lugares estranhos.

Mais uma vez obrigado por sua resposta! Se precisar de mais alguma coisa só falar.

Um grande abraço

![7E8C8B81-36CD-4D74-8E8C-F21EFCF5AC62](https://user-images.githubusercontent.com/51012694/204435977-038fae51-c3a5-4736-afe1-6ee8b0df28f2.jpeg)
![00D9EC98-F88C-46E9-966D-B3C95AC56D6F](https://user-images.githubusercontent.com/51012694/204436000-f074cefa-ae5d-460b-955b-dfde469eb30e.jpeg)
![4B3C191D-11B2-407C-8C30-C3F020452E90](https://user-images.githubusercontent.com/51012694/204436036-eea16ac3-a6a9-44b1-ab3c-cc941736c768.jpeg)
![0FB3E39F-BC1E-418A-A257-A9E6F91D0DAA](https://user-images.githubusercontent.com/51012694/204436074-2beb0c43-e7ff-41be-83f4-b591e776b4d7.jpeg)
![541C2AC2-2404-4986-A9B3-5E33F825ED89](https://user-images.githubusercontent.com/51012694/204436083-30417193-1ebf-436c-b58c-bdeb8836109b.jpeg)
![4381213A-1DB7-45F9-B19E-4479B38B15CE](https://user-images.githubusercontent.com/51012694/204436127-94e73410-6d18-4dc3-aaab-2294ffd52d46.jpeg)
![EB1A100D-2B6A-4CCC-BEBE-3E3B2182EF6C](https://user-images.githubusercontent.com/51012694/204436148-0bb736e5-9aba-4d5b-b4c4-3c92cd95cbc1.jpeg)
![307EB0EB-10D1-458A-80C6-BFA9C1C7F4AB](https://user-images.githubusercontent.com/51012694/204436177-02fe861c-1bf8-47ad-b4f2-4dab6c50a1cc.jpeg)
![6C2B0219-AA49-48EF-8796-C7AF87689DA6](https://user-images.githubusercontent.com/51012694/204436237-10bc6d95-cde2-4032-97ad-a9971fe0c2c3.jpeg)
![212EF356-5151-4459-AFCB-C59351FA5290](https://user-images.githubusercontent.com/51012694/204436239-952aa00d-21ea-4abf-acfc-4decea132314.jpeg)
![C0AAF123-A6C1-4AC8-8ED1-E5BA8A9AD7A9](https://user-images.githubusercontent.com/51012694/204436242-816a033d-cb9e-44c8-a5f1-e0b4ec58566a.jpeg)
![12A02274-F1C0-4094-AE86-6A04D857B7B4](https://user-images.githubusercontent.com/51012694/204436467-1f3dc7d0-30b8-4d75-9858-1417f1101883.jpeg)

**Comment by aguiarrdev** [comment]
@yassersous O layout que utiliza a ul como base também foi corrigido na PR #29, junto com a padronização dos métodos de pagamento que solicitou na Issue #25.

**Comment by yassersous** [comment]
Obrigado por isso Matheus! Será de grande ajuda!

Uma dúvida: normalmente o dono do plugin demora quanto tempo para aceitar as alterações e implementar?

**Comment by aguiarrdev** [comment]
@yassersous Não tenho como te informar sobre prazos, mas logo irão começar as validações para o envio de novas versões.

**Comment by yassersous** [comment]
Obrigado Matheus!

**Comment by devaguia** [comment]
@yassersous Esse errro já foi resolvido na última atualização.

psc @ThalitaNsc

**Comment by ThalitaNsc** [comment]
Encerrando pois já está disponivel na atualização do nosso plugin tal correção.
