### ISSUE TITLE
Visualização de Parcelas com juros

### ISSUE THREAD

**Issue by marcosviniciusdesouza650** [YapayPagamentos/woo-yapay#28]
Olá, Então percebemos que o plugin não mostra os acréscimos de juros  das parcelas. 
Isso acaba fazendo que o cliente perca o interesse em compra, ao não saber o quanto de juros que ele vai pagar.
Acredito que muitos já viram isso. Peco que isso seja adicionado. 

Por favor que isso seja colocado logo.
Vou deixar aqui umas capturas de telas de referencia. 

Esse aqui é o de vocês 
![Captura de Tela (45)](https://user-images.githubusercontent.com/114462337/204323470-62dedca2-6b18-48b8-8d20-271b6d4ce1c0.jpg)

Como precisamos que fiquem: 
Pagar me
![Captura de Tela (47)](https://user-images.githubusercontent.com/114462337/204323654-6f6daf7b-0459-40a4-9387-8321fa746c37.png) 

Mercado PAGO
![Captura de Tela (49)](https://user-images.githubusercontent.com/114462337/204325012-ba801b07-5409-4c98-9a25-5a024f06789e.png)

PayPal

![Captura de Tela (51)](https://user-images.githubusercontent.com/114462337/204325052-ba09faff-99db-4f31-bd81-00b4b2c8370f.png)

**Comment by rubenssoto** [comment]
Bom Dia, tudo bem?

Alguma previsão quando que essas melhorias vão ser mergeadas na main?
Existe algum alternativa? Alguma branch que podemos utilizar?
Obrigado

**Comment by fxaviers** [comment]
Alguma previsão de quando será disponibilizado na versão oficial?

**Comment by aguiarrdev** [comment]
@fxaviers Foi disponibilizado na última atualização.

**Comment by ThalitaNsc** [comment]
Problema corrigido.
