### ISSUE TITLE
Adicionar Codigo de Rastreio Não Funcionando

### ISSUE THREAD

**Issue by raf-rodrigues** [YapayPagamentos/woo-yapay#3]
Desde a ultima atualização com o lançamento de adicionar codigo de rastreio essa novidade não funciona perfeitamente.
Quando é feio o envio para Yapay ela não consta no pedido.

**Comment by aguiarrdev** [comment]
@raf-rodrigues Consegue me informar se o erro ainda persiste?

**Comment by aguiarrdev** [comment]
@raf-rodrigues Corrigido na versão 0.5.7 do plugin, lançada no dia 13/03/2022. É possível identificar no changelog presente no arquivo [readme.txt](https://github.com/YapayPagamentos/woo-yapay/blob/master/woo-yapay/readme.txt/#L177)

@ThalitaNsc se possível pode fechar a Issue.

**Comment by ThalitaNsc** [comment]
Boa Tarde, conforme mencionado anteriormente, encerrando pois já foi atualizado.
