### ISSUE TITLE
O plugin possui alguns problemas de código o que desconfigura o site

### ISSUE THREAD

**Issue by nossileee** [YapayPagamentos/woo-yapay#39]
Olá, relatei lá no plugin alguns problemas.

Podem resolver e atualizar ele?

https://wordpress.org/support/topic/o-plugin-possui-alguns-problemas-de-codigo-o-que-desconfigura-o-site/

"Em análise, já descobri 2 problemas no código do plugin, onde ele é responsável por alterar os menus do site, jogando para baixo, e alterando o botão de diminuir produto no carrinho, dando um espaço entre.

Tive que usar esses 2 códigos para resolver:

/* Ajustar alinhamento do Menu do site, Plugin Yapay que desconfigura */

.wd-nav {
padding-bottom: 30px !important;
}
/* Ajustar alinhamento do Botão menos carrinho, Plugin Yapay que desconfigura */

body div.quantity input[type=”button”] {
margin-right:0;
}

Ao desativar o plugin da Yapay, os problemas simplesmente somem.

Poderiam verificar um update do plugin e corrigir isso? Já está a mais de 2 anos sem updates."

Lembrando que milhares de lojas usam essa integração, vocês deveriam no mínimo manter ela sempre atualizada e funcionando, pois de fato, o interesse maior é de vocês em terem mais clientes.

Obrigado.

**Comment by aguiarrdev** [comment]
Bom dia @nossileee.
Pode me indicar o arquivo onde encontrou esse problema?

**Comment by nossileee** [comment]
Olá!

Não seria um "arquivo", e sim ao ativar o plugin, ele zoa toda o site, principalmente os menus, categorias dos produtos, fica tudo desalinhado. E eu por anos, achando que era qualquer outra coisa...

Veja um exemplo de categorias sem a Yapay:
https://imgur.com/i1ysu1B

Veja um exemplo de como ficam as categorias com o plugin da Yapay ativo:
https://imgur.com/TUZa954

Fica desalinhado de tal forma, que as vezes dificulta saber se a categoria está correta.

Como esse simples exemplo acima, é possível identificar isso, ao ativar o plugin, mas ele gera isso em todos os menus do site, principal, submenu e etc.

**Comment by nossileee** [comment]
Resolvido.

**Comment by devaguia** [comment]
@ThalitaNsc @ThiagoDFi  podem fechar esta issue?

**Comment by ThalitaNsc** [comment]
Encerrando essa issue pois já foi solucionada anteriormente.
