### ISSUE TITLE
taxes not comming through

### ISSUE THREAD

**Issue by dfjmulder** [YapayPagamentos/woo-yapay#4]
We are testing with this plugin for a Brazil webshop and the government tax and the creditcard tax does to go through to Yaay. Only the product + shipping cost without tax is charged. 
Am I missing some setting in woocommerce or is there a bug?

**Comment by wagnerjaccoud** [comment]
Com o meu pullrequest resolve este problema. A maior parte dos plugins trabalha com taxas negativas.

**Comment by wagnerjaccoud** [comment]
my version is more functional and handles everything better
https://github.com/wagnerjaccoud/woo-yapay

**Comment by aguiarrdev** [comment]
O problema foi resolvido na PR #23

**Comment by devaguia** [comment]
psc @ThalitaNsc

**Comment by ThalitaNsc** [comment]
Encerrando pois já está disponivel na atualização do nosso plugin tal correção.
