### ISSUE TITLE
woo-yapay não funciona com o endpoint /order-pay/{ORDER_ID} que é uma função nativa do Woo para pagar novamente os pedidos

### ISSUE THREAD

**Issue by nossileee** [YapayPagamentos/woo-yapay#40]
Olá!

Em muitos testes, percebi que o woo-yapay não é compatível com o /order-pay/{ORDER_ID}, segue link para melhor entendimento:
https://woocommerce.com/document/woocommerce-endpoints-2-1/

O que eu estava fazendo? Criei automações para enviar o link para os clientes que nÃo pagaram o pedido, para relembrar e fazer com que eles concluam, só que de fato, não funciona, porque?

Ao enviar o link para o cliente, segue um exemplo para teste:
https://www.bhlfitness.com.br/finalizar-compra/order-pay/23314/?pay_for_order=true&key=wc_order_HpHEg8lUIdxEK

Se você acessar esse link da minha loja, terá acesso a página de pagamento do pedido, só que se eu colocar pagar por pix ou boleto, dá o seguinte erro:
![image](https://github.com/YapayPagamentos/woo-yapay/assets/49837591/ce3cae2c-5a4b-4c70-80f5-5360d749a6b0)

E se eu tentar pelo cartão de crédito, dá o seguinte erro:
![image](https://github.com/YapayPagamentos/woo-yapay/assets/49837591/446088c7-f959-4c48-bb46-a12fbaa2e64e)

Ou seja, essa função nativa do Woocommerce não funciona com o Gateway da Vindi, pois de alguma forma ele não consegue identificar que os campos que ele está querendo, na verdade já foram preenchidos anteriormente no pedido, seria somente ele ler os campos dentro do pedido, pois no link tem o id do pedido, e fazer o pagamento, simples assim, mas não funciona.

Poderiam analisar e resolver isso?

**Comment by aguiarrdev** [comment]
Bom dia @nossileee 
Realmente o plugin atualmente não suporta essa configuração. Vamos trabalhar para implementar essa solução.

Fique atento a essa issue para as próximas informações.

**Comment by nossileee** [comment]
Olá @aguiarrdev , maravilha!

Aguardo ansioso pela melhoria.

Abraços.

**Comment by nossileee** [comment]
Só para complementar, que testei aqui com o Mercado pago e funciona perfeitamente, toda a inteligência que criei para pagar novamente, recuperar pagamento, alterar método, tudo certinho.

O próprio MP gera o link para pagar e novamente, simulei um cartão malsucedido:
https://imgur.com/7gceayE

Ao clicar naquele link, posso pagar o pedido novamente, e funciona corretamente.
Alterei de cartão, para pix, e depois para boleto, tudo no mesmo pedido, sem o cliente ter todo o trabalho de refazer um pedido do zero.

Caso queira usar como exemplo e testar o plugin MP para consertar da Yapay.

Obrigado.

**Comment by nossileee** [comment]
Ops, fechei em querer...

**Comment by nossileee** [comment]
Olá!

Nenhuma solução ainda para esse problema?
Acabei de testar, vi que teve um update do plugin, mas não resolveu nada dos problemas que citamos aqui.

Poderia nos atualizar por gentileza?

**Comment by ThalitaNsc** [comment]
Olá tudo bem? Sou Thalita do time de suporte técnico.

Subimos uma versão que te dá a alternativa de vendas para clientes PJ sem a obrigatoriedade do CPF, ela é setada dentro das configurações do método de pagamento do plugin Vindi Pagamentos(Yapay).
Mesmo com essa configuração setada se faz necessário entrar em contato com o nosso time de suporte da Vindi, abrindo um ticket conosco para solicitar que essa funcionalidade de vendas para PJ sem a obrigatoriedade de CPF seja ativada para sua conta. Caso não solicite a ativação da funcionalidade junto ao nosso suporte, mesmo com a configuração ativa dentro do plugin a venda dará erro.

Para nos contatar para realizar tal atualização é possível acessar ao nosso [chat online](https://myaccount.yapay.com.br/contact-us/) dentro do portal do Intermediador no botão 'Fale conosco'. O botão do chat fica do lado direito inferior.
![image](https://github.com/YapayPagamentos/woo-yapay/assets/77510375/89b199ec-ccea-49f1-9d3a-77545efd8bce)


Qualquer dúvida estou totalmente a disposição.

Atenciosamente,
Thalita Nascimento.
