### ISSUE TITLE
Plugin adiciona CSS que causa problema de formatação no layout do site

### ISSUE THREAD

**Issue by denisgomesfranco** [YapayPagamentos/woo-yapay#42]
Pois é, essa é nova 😅 Olha o print: https://imgur.com/a/DMe1O9E

Nesse template o menu utiliza elementos `ul` e `li`. E o arquivo `/wp-content/plugins/woo-yapay/assets/css/styles.css?ver=0.1.0` traz a regra `margin-top: 30px;` para o elemento `ul` que acaba atrapalhando o menu e outros elementos visuais do site, quando essa regra deveria ser restrita somente aos conteúdos do plugin em si.

Tive de acrescentar uma regra `margin: unset;` para resolver o problema de momento, mas vocês deveriam olhar isso daí.

**Comment by nossileee** [comment]
Sim @denisgomesfranco , relatei a mesma coisa aqui:

https://github.com/YapayPagamentos/woo-yapay/issues/39

**Comment by denisgomesfranco** [comment]
Não tinha visto @nossileee , obrigado!

**Comment by aguiarrdev** [comment]
@denisgomesfranco @nossileee Bom dia. Acabei de enviar uma PR removendo esse estilo, entre outras correções.

**Comment by nossileee** [comment]
Bom dia @aguiarrdev !

Ótimo! Quando esse update vai estar disponível?

**Comment by aguiarrdev** [comment]
Opa @nossileee . Já está disponível no repositório oficial do WordPress.

**Comment by nossileee** [comment]
Fala @aguiarrdev , maravilha!

Testei e ficou muito bom, pude remover alguns códigos css dos sites, ficou bem melhor.

Só ainda percebi, que os menus e listagem de categorias na parte administrativa, ainda são afetados no alinhamento.

Vou te mandar um exemplo aqui:
Se eu acessar aparência -> Menu e olhar as opções com o site sem o plugin da Vindi, fica assim:
![image](https://github.com/YapayPagamentos/woo-yapay/assets/49837591/06401ff6-7255-4553-8ef3-40c91fae1294)

Opção de seleção e título bem alinhados.

Se eu faço a mesma coisa em um site que possui o plugin da vindi, veja como fica:
![image](https://github.com/YapayPagamentos/woo-yapay/assets/49837591/6c7827bb-7b6c-4f18-a353-652f6ab2ff77)

Veja que o quadro de seleção fica acima do título, o que as vezes acaba confundindo qual caixa, faz parte de qual título.

Facilmente você consegue simular seguindo isso.

No mais, ficou muito bom os ajustes, Muito Obrigado.

**Comment by devaguia** [comment]
Entendi @nossileee. 
Estranho isso. Agora no plugin todas as regras css estão apontando para classes e IDs específicos. Acredito que pode ser algo relacionado a cache do seu navegador. Já realizou algum teste em guia anônima?

Acha que consegue inspecionar o elemento e me informar de onde está vindo essa estilização?

**Comment by nossileee** [comment]
Cara, fui consultar agora novamente e parece estar tudo ok.

Poderia ser algum cache sim hehe, fiz update do tema e de outros plugins e limpei 100% do cache.

Que maravilha. Resolvido então. Muito grato pela ajuda.

**Comment by devaguia** [comment]
@nossileee Bacana! Obrigado!

@ThalitaNsc @ThiagoDFi Podem fechar esta?

**Comment by ThalitaNsc** [comment]
Oi encerrando pois já encontra-se implementada correção.
