### ISSUE TITLE
Ao selecionar Pessoa Jurídica e Boleto, o campo CPF é exibido

### ISSUE THREAD

**Issue by alantygel** [YapayPagamentos/woo-yapay#44]
Olá,

No site do meu cliente, é possível fazer compras como pessoa jurídica. Porém, ao selecionar a opção boleto, o plugin pede o CPF (e não CNPJ) para emissão do boleto.

Seria importante que ele conseguisse gerar o boleto usando o CNPJ já preenchido.

obrigado

**Comment by ThalitaNsc** [comment]
Olá tudo bem? Sou Thalita do time de suporte técnico. 

Subimos uma versão que te dá a alternativa de vendas para clientes PJ sem a obrigatoriedade do CPF, ela é setada dentro das configurações do método de pagamento do plugin Vindi Pagamentos(Yapay). 
Mesmo com essa configuração setada se faz necessário entrar em contato com o nosso time de suporte da Vindi, abrindo um ticket conosco para solicitar que essa funcionalidade de vendas para PJ sem a obrigatoriedade de CPF seja ativada para sua conta. Caso não solicite a ativação da funcionalidade junto ao nosso suporte, mesmo com a configuração ativa dentro do plugin a venda dará erro.

Qualquer dúvida estou totalmente a disposição.

Atenciosamente,
Thalita Nascimento.

**Comment by MarcosLye** [comment]
Olá muito obrigado pelas informações, por qual canal eu realizo esse contato para essa alteração?

Best Regards
________________________________

**Comment by ThalitaNsc** [comment]
Oi é possível acessar ao nosso [chat online](https://myaccount.yapay.com.br/contact-us/) dentro do portal do Intermediador no botão 'Fale conosco'. O botão do chat fica do lado direito inferior.
![image](https://github.com/YapayPagamentos/woo-yapay/assets/77510375/8c8ccdc9-70d9-4781-88d7-dc9cf6f2f6e8)

**Comment by MarcosLye** [comment]
Muito obrigado pelas informações. Realizei os testes e a função funcionou bem.

Notei que a forma de pagamento no cartão, os ícones das bandeiras ficam de tamanho desproporcional.

Poderia verificar se seria algo no plugin?

Muito obrigado,

[cid:558d276c-5a61-4654-9eeb-0a61571bc62e]


Best regards,

https://gopresence.com.br/

[cid:a55dbb6f-e8be-4676-8a9f-cffb6c0dd5f6]<https://gopresence.com.br/>
________________________________
De: ThalitaNsc ***@***.***>
Enviado: segunda-feira, 2 de outubro de 2023 19:32
Para: YapayPagamentos/woo-yapay ***@***.***>
Cc: Marcos Alexandre ***@***.***>; Manual ***@***.***>
Assunto: Re: [YapayPagamentos/woo-yapay] Ao selecionar Pessoa Jurídica e Boleto, o campo CPF é exibido (Issue #44)


Oi é possível acessar ao nosso chat online<https://myaccount.yapay.com.br/contact-us/> dentro do portal do Intermediador no botão 'Fale conosco'. O botão do chat fica do lado direito inferior.
[image]<https://user-images.githubusercontent.com/77510375/272102772-8c8ccdc9-70d9-4781-88d7-dc9cf6f2f6e8.png>

**Comment by ThalitaNsc** [comment]
Boa tarde @MarcosLye A sua seção da lateral está muito estreita, mas não é o nosso plugin que está modificando esse layout, você consegue alterar esse layout diretamente com os ajustes de front do seu tema.
