### ISSUE TITLE
Ícones forma de pagamento no checkout muito grande.

### ISSUE THREAD

**Issue by MarcosLye** [YapayPagamentos/woo-yapay#45]
Estamos enfrentando um problema na versão 0.6.5 que exibe os ícones de pagamento do WooCommerce (Boleto, Cartão e PIX) na página de checkout em um tamanho gigante desconfigurando toda a página.
Provisoriamente fizemos um downgrade para a versão 0.6.4 que exibe os ícones corretamente.

No suporte orientaram a inserir a seguinte regra CSS
#payment .payment_methods li label img {
        float: right; max-height: 1.618em;
}
Que corrigiu a dimensão dos ícones até uma nova atualização.

**Comment by aguiarrdev** [comment]
Bom dia @MarcosLye. Acabei de enviar uma correção para este problema, após validação será enviado como uma nova atualização.

**Comment by ThalitaNsc** [comment]
Encerrando pois já está disponivel na atuaolização do nosso plugin tal correção.
