### ISSUE TITLE
parcelamento sem, juros para o plugin diz que é com juros

### ISSUE THREAD

**Issue by nossileee** [YapayPagamentos/woo-yapay#48]
Olá @devaguia , dá uma olhada nisso.

Deveria ser sem juros, mas aparece com juros.
![image](https://github.com/YapayPagamentos/woo-yapay/assets/49837591/4a132f30-89a1-40e2-8125-2eda6709dbd7)
![image](https://github.com/YapayPagamentos/woo-yapay/assets/49837591/9ade8c24-e94d-47a3-9113-33876a4e92e8)

Nesse outro teste:
![image](https://github.com/YapayPagamentos/woo-yapay/assets/49837591/9ede82e7-925c-458d-a8b9-74e6be112a43)
![image](https://github.com/YapayPagamentos/woo-yapay/assets/49837591/c4c8a72f-ed3a-4123-bc9b-7367498d00d9)

Fica igual ao outro, os clientes estão reclamando que "tem juros" mas na verdade não tem.

Tive que deixar assim por enquanto: (não exibir)
![image](https://github.com/YapayPagamentos/woo-yapay/assets/49837591/a315a5ab-1925-4a9b-8912-d8d368f2f73e)

Consegue corrigir isso tb?

**Comment by devaguia** [comment]
Pode fechar @ThalitaNsc

**Comment by ThalitaNsc** [comment]
Boa tarde, sou Thalita do time de suporte técnico. 

A nova versão 0.6.7 do plugin contempla esse cenário, agora o calculo dos juros do parcelamento é efetivado com sucesso e a parcela ao lado vem explicando se é com ou sem juros. 

![image](https://github.com/YapayPagamentos/woo-yapay/assets/77510375/c0e54460-4f88-4f8f-b75e-edaa6dc23061)
