### ISSUE TITLE
block is not a function

### ISSUE THREAD

**Issue by neuberoliveira** [YapayPagamentos/woo-yapay#9]
Quando chego no checkout apos colocar os numeros do cartao tenho esse erro

```javascript
Uncaught TypeError: jQuery(...).addClass(...).block is not a function
```

Mesmo ja tendo incluido a blockui [desse link](https://github.com/malsup/blockui/blob/master/jquery.blockUI.js)

unica solucao no momento foi editar o js do plugin e deixar assim

```javascript
beforeSend: function (xhr){
            jQuery('form.checkout').addClass( 'processing' );
            // jQuery('form.checkout').addClass( 'processing' ).block({
            //         message: null,
            //         overlayCSS: {
            //                 background: '#fff',
            //                 opacity: 0.6
            //         }
            // });
        }
```

**Comment by aguiarrdev** [comment]
@neuberoliveira Sabe me informar se o erro ainda persiste?

**Comment by aguiarrdev** [comment]
Não consegui reproduzir o erro informado pelo cliente. 
Me parece um conflito com o JQuery do cliente. Muito provável que os scripts do JQuery não estavam sendo carregados corretamente no site.

@ThalitaNsc Se possível pode fechar essa.

**Comment by ThalitaNsc** [comment]
Encerrado por inatividade
